Experimental fix to flaky 5xx errors
We had a series of flaky errors in `SingleReferralEndpoints` test class
```
Test sp user works for prime provider and has required contract group(Request) (request=AssignSentReferral) FAILED

java.lang.AssertionError: Range for response status value 500 INTERNAL_SERVER_ERROR expected:<SUCCESSFUL> but was:<SERVER_ERROR>
    at uk.gov.justice.digital.hmpps.hmppsinterventionsservice.integration.authorization.SingleReferralEndpoints.sp user works for prime provider and has required contract group(SingleReferralEndpoints.kt:167)
```

When logs were added, the errors reduced significantly, hinting at async
timing problems

Then the caught exception said:
```
> POST http://localhost:39473/sent-referral/24121550-20ff-421b-b39f-72a1abca1c77/assign

{"status":500,"error":"unexpected error","message":"Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Error while committing the transaction"}
```
which further points to async timing issues

--

Facts:
- The documentation of `exchange()` says "Perform the exchange without a
  request body"
- Only the `expectStatus` assertions were throwing these errors, based
  on the test history, none with `expectBody`

Hypothesis: the test assertion is processed as soon as the response
headers are read, then moves on, creating a race condition

Experimental solution: make all assertions depend on the full resolution
of the response body, thus forcing the request to complete before moving
on

(Is there a better way?)