Bump gradle's max memory to 512MB (from 256MB)
The previous value is defined in the hmpps orb and coming from the
`executor: hmpps/java` setting

This change is because we started seeing
```
> Task :compileTestKotlin
Exception: java.lang.OutOfMemoryError
```
on CI