Create script to ensure stable dependency boot
TL;DR: Booting community-api first, then hmpps-auth, then the rest will
ensure a stable boot order without excessive restarts and CPU load.

---

Every application is dependent on `hmpps-auth` being responsive;
otherwise, they end up with

```
org.springframework.web.client.ResourceAccessException: ⏎
  I/O error on GET request for ⏎
  "http://hmpps-auth:8090/auth/issuer/.well-known/openid-configuration"
```

In turn, `hmpps-auth` requires `community-api` to be responsive during
boot, resulting in
```
reactor.core.Exceptions$ReactiveException: ⏎
  java.net.UnknownHostException: failed to resolve 'community-api' after 2 queries
```

This forces the boot order described in the script.